# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  #imports =
  #  [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  #  ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/56901013-5bcd-435c-83b6-8b90539068f5";
    fsType = "ext4";
  };
  
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/057D-C047";
    fsType = "vfat";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0c7ce641-f70b-4bde-b34e-d942b798e253"; }
    ];

  boot.initrd.luks.devices = {
    cryptlvm = {
      device = "/dev/disk/by-uuid/a52ead7d-6ec7-446b-893b-bee7ef392004";
      preLVM = true;
      allowDiscards = true;
    };
  };
 
  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
