# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  #imports =
  #  [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  #  ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e3e28c20-ed59-48df-a9f7-657966718dc7";
    fsType = "ext4";
  };
  
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6F6C-9CCD";
    fsType = "vfat";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fdf854d3-dab8-4c1a-b86b-ce050a4633f1"; }
    ];

  boot.initrd.luks.devices = {
    cryptlvm = {
      device = "/dev/disk/by-uuid/a52ead7d-6ec7-446b-893b-bee7ef392004";
      preLVM = true;
      allowDiscards = true;
    };
  };
 
  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
